### ISSUE TITLE
How to use it for changed Bear token

### ISSUE THREAD

**Issue by lorenpan** [JakimLi/pandaria#10]
After I reviewed the introduction and code I found the stationary token is saved in application.properties file:
http.headers.Authorization=Bear Token
http.headers.global=globalHeader

http.headers.will_be_overrided=not_overrided
But if the Bear token will be expired after a period, and need to call a custom method to generate a new token, such as call "/tokens/generate?entity-id=" API to generate before test, how can I use the project for cucumber-api testing?

**Comment by JakimLi** [comment]
The token in `application.properties` is designed for global usage, it can be override by `header` key word.

Which means you can call your api, and extract your token from response and assign it to a variable, and then use the `header` keyword for your request, something like:

```
* uri: your_token_refresh_address
* send: GET
* var: your_token<-'$.refreshd_token'

# in your next request
* uri: some_other_uri
* header: 'Authorization'="${your_token}""
....
 
```

**Comment by lorenpan** [comment]
Thanks for the quick feedback, I know the means of the example, but I have a detailed case for my current project:
The generated token is in the response body with html format but not json, such as:
<html>
  <body bgcolor="#dddddd">
    <table bgcolor="#dddddd" border="1">
      <tr>
        <td colspan="1" rowspan="1" valign="top">
          <b>jwt</b>
        </td>
        <td colspan="1" rowspan="1">**_The_generated_token_value_**</td>
      </tr>
    </table>
  </body>
</html>
I need to use a custom method to pick up the token firstly and then set it in the "your_token" of the example above, so I can't use '$.refreshd_token' to get the token directly, and I'd like to know is that possible to achieve the goal?

**Comment by JakimLi** [comment]
You can write your own cucumber steps, and put your token into pandaria's variables, something like below:

```

public class YourOwnSteps {

    @Autowired
    Variables variables;

    @Then("refresh token")
    public void refreshToken() throws IOException {
        // call your refresh endpoint and parse your jwt token from the html response
        variables.assign("refreshed_token", refreshed_token);
    }
}
```

Then you should be able to use it like:

```
...

* refresh token
* uri: your api uri
* header: 'Authorization'="$refreshed_token"

...
```

**Comment by lorenpan** [comment]
Got it, I will have a try with it, thanks a lot for your help!
