### ISSUE TITLE
Multipart file upload

### ISSUE THREAD

**Issue by ssreejithmails** [JakimLi/pandaria#8]
Is Multi-part requests currently supported?

**Comment by JakimLi** [comment]
Multipart request is used for attachment feature, if you want to use multipart request to upload a file, it's supported, you can try to use `attachment`, 

there is an example in the document:

https://github.com/JakimLi/pandaria/blob/master/doc/usage.md#upload-file

let me know if it does not suit your needs. :)

**Comment by ssreejithmails** [comment]
thanks for the response. I am looking for a way to send a file along and JSON form data(FormDataMultiPart).

I see that the attachment method inside HttContext adds a bodyPart. Is there a way to add a filed as well?

**Comment by JakimLi** [comment]
You're right about the code, I understand your requirement, I will release a new version later to include your suggestion.

**Comment by ssreejithmails** [comment]
Thank you. Waiting for the release. 👍😀

**Comment by JakimLi** [comment]
Released 0.3.2, please have a look at https://github.com/JakimLi/pandaria/blob/master/doc/usage.md#form

**Comment by ssreejithmails** [comment]
Thanks for the speedy release... I see the changes.. I will close this issue..
