### ISSUE TITLE
怎么在.feature文件中指定代理，使用maven

### ISSUE THREAD

**Issue by lingting-gzm** [JakimLi/pandaria#9]
如题，我只有一个 .feature 文件，我该怎么使用代理，我想使用fiddle捕获请求

**Comment by JakimLi** [comment]
Maven可以使用如下命令来指定代理

```
mvn -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=8866 clean test
```

不同版本的maven可能添加的方式不一样，比如有些需要手动添将 `-Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=8866` 放到环境变量 MAVEN_OPTS中，maven 3.3.1以上的版本可以在项目根目录下创建一个`.svn/jvm.config`的文件，然后将其放到这个文件里面。如果一种方式不行的话，可以尝试一下其他的方式。

IDE中可以通过类似的添加JVM系统参数来指定代理，如IDEA中，编辑Run Configuration:

![image](https://user-images.githubusercontent.com/4111971/93664770-f37ead00-faa3-11ea-97fc-671c9ee7379b.png)

**Comment by lingting-gzm** [comment]
> Maven可以使用如下命令来指定代理
> 
> ```
> mvn -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=8866 clean test
> ```
> 
> 不同版本的maven可能添加的方式不一样，比如有些需要手动添将 `-Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=8866` 放到环境变量 MAVEN_OPTS中，maven 3.3.1以上的版本可以在项目根目录下创建一个`.svn/jvm.config`的文件，然后将其放到这个文件里面。如果一种方式不行的话，可以尝试一下其他的方式。
> 
> IDE中可以通过类似的添加JVM系统参数来指定代理，如IDEA中，编辑Run Configuration:
> 
> ![image](https://user-images.githubusercontent.com/4111971/93664770-f37ead00-faa3-11ea-97fc-671c9ee7379b.png)

谢谢，idea配置方式可行!
